version: '4'

services:

  redis:
    image: redis
    ports:
      - '6380:6379'

  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_DB=habits
    volumes:
      - pg_data:/var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5


  app:
    build: .
    tty: true
    command: sh -c "sleep 3 && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - '8000:8000'
    depends_on:
      db:
        condition: service_healthy

  celery:
    build: .
    tty: true
    env_file:
      - .env
    command:  sh -c "sleep 5 &&  celery -A config worker -l INFO"
    depends_on:
      - redis
      - app

  celery_beat:
    build: .
    tty: true
    env_file:
      - .env
    restart: always
    command:  sh -c "sleep 7 &&  celery -A config beat -l INFO -S django"
    depends_on:
      - celery
      - redis
      - app

volumes:
  pg_data:
